name: 'Fetch Weather Data'
description: 'Fetch weather data for the specified location'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  username:
    description: 'GitHub username (for logs)'
    required: true

outputs:
  skip:
    description: 'Whether this step should be skipped (true/false)'
    value: ${{ steps.fetch.outputs.skip }}

runs:
  using: 'composite'
  steps:
    - name: ðŸŒ¦ï¸ Fetch Weather Data
      id: fetch
      shell: bash
      env:
        GITHUB_OWNER: ${{ inputs.username }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OUTPUT_DIR: weather
      run: |
        mkdir -p weather logs/weather
        
        echo "Fetching weather data..."
        if ! scripts/fetch-weather.sh > weather/weather.json.tmp 2>> logs/weather/weather.log; then
          echo "âš ï¸ Warning: Failed to fetch weather data"
          echo "Using cached data if available"
          if [ ! -f weather/weather.json ]; then
            echo '{"error": "Failed to fetch data"}' > weather/weather.json
          fi
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          if jq empty weather/weather.json.tmp 2>/dev/null; then
            mv weather/weather.json.tmp weather/weather.json
            echo "âœ… Weather data fetched successfully"
            echo "skip=false" >> $GITHUB_OUTPUT
          else
            echo "âš ï¸ Warning: Invalid JSON in weather file"
            rm -f weather/weather.json.tmp
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
        fi
