name: 'Setup Environment'
description: 'Set up the development environment with checkout, Python, and dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  install-jq:
    description: 'Install jq'
    required: false
    default: 'true'
  install-curl:
    description: 'Install curl'
    required: false
    default: 'true'
  install-python-deps:
    description: 'Install Python dependencies from requirements.txt'
    required: false
    default: 'true'
  extra-apt-packages:
    description: 'Additional apt packages to install (space-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        PACKAGES=""
        if [ "${{ inputs.install-jq }}" = "true" ]; then
          PACKAGES="$PACKAGES jq"
        fi
        if [ "${{ inputs.install-curl }}" = "true" ]; then
          PACKAGES="$PACKAGES curl"
        fi
        if [ -n "${{ inputs.extra-apt-packages }}" ]; then
          PACKAGES="$PACKAGES ${{ inputs.extra-apt-packages }}"
        fi
        if [ -n "$PACKAGES" ]; then
          sudo apt-get install -y $PACKAGES
        fi

    - name: Install Python dependencies
      if: inputs.install-python-deps == 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
