name: 'Generate Location Card'
description: 'Generate the location card SVG'

inputs:
  input-json:
    description: 'Path to the location data JSON file'
    required: false
    default: 'location/location.json'
  output-svg:
    description: 'Path to the output SVG file'
    required: false
    default: 'location/location-card.svg'
  map-image:
    description: 'Path to the location map image'
    required: false
    default: 'location/location-map.png'

runs:
  using: 'composite'
  steps:
    - name: 📍 Generate Location Card
      shell: bash
      run: |
        echo "Generating location card..."
        if python scripts/incremental-generate.py "${{ inputs.input-json }}" "${{ inputs.output-svg }}" scripts/generate-location-card.py location "${{ inputs.map-image }}"; then
          echo "✅ Location card generated successfully"
        else
          echo "⚠️ Warning: Failed to generate location card"
          # Create fallback card
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400"><text x="400" y="200" text-anchor="middle" fill="#666">Location Card Unavailable</text></svg>' > "${{ inputs.output-svg }}"
        fi
