name: 'Setup Profile Engine'
description: 'Install Profile Engine CLI and dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - name: ðŸ Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt
          **/pyproject.toml
          engine/pyproject.toml
    
    - name: ðŸ“¦ Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl bc
    
    - name: ðŸ”§ Create Python virtual environment
      shell: bash
      run: |
        python3 -m venv .venv
        echo "âœ… Virtual environment created at .venv"
    
    - name: ðŸ“¦ Install Profile Engine
      shell: bash
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e ./engine
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
        echo "âœ… Profile Engine installed in virtual environment"
        # Verify installation works within the activated venv
        which profile-engine
        profile-engine --version
    
    - name: ðŸ“¦ Install legacy dependencies (for backward compatibility)
      shell: bash
      run: |
        source .venv/bin/activate
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        echo "âœ… Legacy dependencies installed in virtual environment"
