name: 'Update README with Cards'
description: 'Update README.md with all generated SVG cards'

runs:
  using: 'composite'
  steps:
    - name: 📝 Update README with All Cards
      shell: bash
      run: |
        echo "Updating README with all cards..."
        
        # Update developer dashboard
        if [ -f "developer/developer_dashboard.svg" ]; then
          python scripts/update-readme.py \
            --marker DEVELOPER-DASHBOARD \
            --content '<img src="./developer/developer_dashboard.svg" alt="Developer Dashboard" width="100%"/>' || true
        fi
        
        # Update quote card
        if [ -f "quotes/quote_card.svg" ]; then
          python scripts/update-readme.py \
            --marker QUOTE-CARD \
            --content '<img src="./quotes/quote_card.svg" alt="Quote of the Day" width="100%"/>' || true
        fi
        
        # Update weather card
        if [ -f "weather/weather-today.svg" ]; then
          python scripts/update-readme.py \
            --marker WEATHER-CARD \
            --content '<img src="./weather/weather-today.svg" alt="Today'\''s Weather" width="100%"/>' || true
        fi
        
        # Update location card
        if [ -f "location/location-card.svg" ]; then
          python scripts/update-readme.py \
            --marker LOCATION-CARD \
            --content '<img src="./location/location-card.svg" alt="My Location" width="100%"/>' || true
        fi
        
        # Update SoundCloud card
        if [ -f "assets/soundcloud-card.svg" ] && [ -f "assets/metadata.json" ]; then
          PERMALINK_URL=$(jq -r '.permalink_url // "#"' assets/metadata.json)
          CARD_CONTENT='<a href="'"${PERMALINK_URL}"'" target="_blank" rel="noopener noreferrer"><img src="assets/soundcloud-card.svg" alt="SoundCloud Latest Track" width="100%"/></a>'
          python scripts/update-readme.py \
            --marker SOUNDCLOUD-CARD \
            --content "${CARD_CONTENT}" || true
        fi
        
        # Update Oura health card
        if [ -f "oura/health_dashboard.svg" ]; then
          python scripts/update-readme.py \
            --marker OURA-HEALTH-CARD \
            --content '<img src="./oura/health_dashboard.svg" alt="Oura Health Dashboard" width="100%"/>' || true
        fi
        
        # Update Oura mood card
        if [ -f "oura/mood_dashboard.svg" ]; then
          python scripts/update-readme.py \
            --marker OURA-MOOD-CARD \
            --content '<img src="./oura/mood_dashboard.svg" alt="Oura Mood Dashboard" width="100%"/>' || true
        fi
        
        echo "✅ README updated with all available cards"
